import { StyleSheet, Platform, Dimensions } from 'react-native';

const { height } = Dimensions.get('window');
const { width } = Dimensions.get('window');
const CANVAS_SIZE = width - 20;

export const getStyles = (aplicarEscala) => StyleSheet.create({
  // --- ESTILOS GENERALES Y CONTENEDORES ---
  container: { 
    flex: 1, 
    backgroundColor: '#F0F5FA',
  },
  contentCenter: {
    flex: 1,
    justifyContent: 'center', 
    alignItems: 'center',
    paddingHorizontal: 30,
  },
  contentPadding: {
    flex: 1,
    paddingHorizontal: 25,
    paddingTop: 20,
  },

  // --- TOP BAR / HEADER ---
  topBar: {
    backgroundColor: '#FFFFFF',
    width: '100%',
    paddingTop: Platform.OS === 'ios' ? 30 : 20, 
    paddingBottom: 20,
    paddingHorizontal: 25,
    borderBottomWidth: 1,
    borderBottomColor: '#E2E8F0',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
  },
  topBarArrow:{
    fontSize:aplicarEscala(26),
    color:"#334155"
  },
  logoRow: { 
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between', 
    width: '100%', 
  },
  logoHeader: { 
    width: 60, 
    height: 60, 
    marginRight: 55, 
  },
  textContainer: {
    justifyContent: 'center',
  },
  brandName: { 
    fontSize: aplicarEscala(22), 
    fontWeight: '800', 
    color: '#1A202C',
    marginLeft: 15
  },
  subtitle: { 
    fontSize: aplicarEscala(13), 
    color: '#718096', 
    fontWeight: '400'
  },

  // --- BOTONES TIPO CARD (Bienvenida) ---
  buttonWrapper: { 
    width: '100%', 
  },
  cardButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    padding: 20,
    borderRadius: 18,
    marginBottom: 16,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 10,
  },
  iconCircle: {
    width: 50,
    height: 50,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  cardButtonText: { 
    fontSize: aplicarEscala(18), 
    fontWeight: '600', 
    color: '#2D3748' 
  },

  // --- FORMULARIOS (Registro/Login) ---
  label: {
    fontSize: aplicarEscala(14),
    fontWeight: '600',
    color: '#4A5568',
    marginBottom: 8,
    marginTop: 15,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingHorizontal: 15,
    height: 55,
  },
  inputIcon: {
    marginRight: 10,
    fontSize: aplicarEscala(22),      
    color: '#94A3B8'
  },
  input: {
    flex: 1,
    color: '#2D3748',
    fontSize: aplicarEscala(16),
  },
  eyeIcon: {
    padding: 5,
  },
  dateDisplay: {
    flex: 1,
    fontSize: aplicarEscala(16),
    textAlignVertical: 'center',
  },

  // --- BOTONES DE ACCIÓN (Bottom) ---
  footer: {
    paddingHorizontal: 25,
    paddingBottom: 30, 
    backgroundColor: '#F0F5FA',
  },
  mainButton: {
    backgroundColor: '#334155',
    height: 55,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#1D4ED8',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
  },
  mainButtonText: {
    color: '#FFFFFF',
    fontSize: aplicarEscala(16),
    fontWeight: '700',
  },
  loginLink: { 
    marginTop: 10,
    alignItems: 'center'
  },
  loginText: { 
    color: '#334155', 
    fontSize: aplicarEscala(15), 
    fontWeight: '500',
    textDecorationLine: 'underline'
  },

  // --- ELEMENTOS FLOTANTES (Bot de ayuda) ---
  botPosition: {
    position: 'absolute',
    bottom: 35,
    alignSelf: 'center',
  },
  botCircle: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: '#FFF9C4', 
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
  },
  botImage: {
    width: 45,
    height: 45,
  },

  // --- MENSAJES ---
  message: {
    color: '#E53E3E',
    textAlign: 'center',
    marginTop: 10,
    fontSize: aplicarEscala(14),
  },
  // --- NUEVOS: DASHBOARD ESPECÍFICOS ---
  headerUserInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  dateContainer: {
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 5,
  },
  dateText: {
    color: '#718096',
    fontSize: aplicarEscala(16),
    left: 60,
    fontWeight: '500',
  },
  headerIconButton: {
    padding: 8,
    borderRadius: 12,
    backgroundColor: '#F7FAFC',
    marginLeft: 10,
  },
  menuCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 15, 
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    marginHorizontal: 4,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 10,
  },
  menuIconContainer: {
    width: 65, 
    height: 65,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  menuTitle: {
    fontSize: aplicarEscala(18),
    fontWeight: '700',
    color: '#2D3748',
  },
  menuSubtitle: {
    fontSize: aplicarEscala(14),
    color: '#718096',
    marginTop: 2,
  },
  tabItem: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabText: {
    fontSize: aplicarEscala(11),
    fontWeight: '600',
    color: '#94A3B8',
    marginTop: 4,
  },
  tabTextActive: {
    color: '#334155',
  },
  scrollContent: {
    paddingHorizontal: 20, 
    paddingTop: 15,
    paddingBottom:30,
  },
messageWrapper: {
    marginBottom: 15,
  },
  // --- SECCIÓN DE PERFIL (Sin borde de card, más limpio) ---
  profileSection: {
    paddingVertical: 10,
    marginBottom: 20,
  },

  // --- LÍNEA DIVISORA CON TEXTO ---
  dividerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 25,
  },
  dividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#E2E8F0',
  },
  dividerText: {
    marginHorizontal: 15,
    fontSize: aplicarEscala(14),
    fontWeight: '700',
    color: '#94A3B8',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },

  // --- TARJETAS DE CONFIGURACIÓN (Mantienen el estilo card) ---
  settingsCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    marginBottom: 15,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
  },
  // --- ELEMENTOS DE INTERACCIÓN EN AJUSTES ---
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  sectionTitle: {
    fontSize: aplicarEscala(18),
    fontWeight: '700',
    color: '#2D3748',
    marginLeft: 10,
  },
  optionButton: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
    marginBottom: 10,
    backgroundColor: '#FFFFFF',
  },
  optionButtonActive: {
    borderColor: '#4D6BFE',
    backgroundColor: '#F0F5FF',
    borderWidth: 2,
  },
  optionText: {
    fontSize: aplicarEscala(16),
    color: '#4A5568',
    fontWeight: '600',
  },
  optionTextActive: {
    color: '#4D6BFE',
    fontWeight: '700',
  },
  rowSpace: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  avatarCircle: {
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: '#E8F0FE',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: 20,
  },
  // --- ESTILOS PARA LA FOTO DE PERFIL ---
  profilePhotoContainer: {
    alignSelf: 'center',
    marginBottom: 25,
    position: 'relative',
  },
  photoCircle: {
    width: 130,
    height: 130,
    borderRadius: 65,
    backgroundColor: '#E8F0FE', 
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
  },
  editPhotoButton: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: '#334155',
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    paddingHorizontal: 5,
  },
  typeCard: {
    backgroundColor: '#FFFFFF',
    width: '48%', 
    borderRadius: 24,
    padding: 20,
    marginBottom: 16,
    alignItems: 'center',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
  },
  typeCardActive: {
    borderColor: '#4D6BFE',
    backgroundColor: '#F0F5FF',
    borderWidth: 2,
  },
  badgeText: {
    fontSize: 10,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  typeIconCircle: {
    width: 70,
    height: 70,
    borderRadius: 35,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  typeText: {
    fontSize: aplicarEscala(14),
    color: '#718096',
    fontWeight: '500',
    textAlign: 'center',
  },
  typeTextActive: {
    color: '#4D6BFE',
    fontWeight: '700',
  },
  gridRecordatorios: {
    flexDirection: 'row',
    flexWrap: 'wrap', 
    justifyContent: 'space-between',
    width: '100%',
  },
  cardTipoRecordatorio: {
    width: '48%', 
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    paddingVertical: 15,
    alignItems: 'center',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    elevation: 2,
  },
  optionButton: {
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  // --- ESTILOS DEL CHATBOT ---
  chatContainer: {
    flex: 1,
    backgroundColor: '#FFFCF5', 
  },
bubbleBot: {
    alignSelf: 'flex-start',
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 20,
    borderBottomLeftRadius: 4, 
    maxWidth: '85%',
    elevation: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
  },
bubbleUser: {
    alignSelf: 'flex-end',
    backgroundColor: '#334155', 
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 20,
    borderBottomRightRadius: 4,
    maxWidth: '85%',
  },
  textBot: {
    color: '#4A5568',
    fontSize: aplicarEscala(16),
    lineHeight: 22,
  },
  textUser: {
    color: '#FFFFFF',
    fontSize: aplicarEscala(16),
    lineHeight: 22,
  },
chatInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 5,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderColor: '#E2E8F0',
  },
 inputChatWrapper: {
    flex: 1,
    height: 35,
    backgroundColor: '#F1F5F9',
    borderRadius: 20,
    paddingHorizontal: 15,
    marginRight: 10,
  },
  sendButton: {
    backgroundColor: '#334155',
    width: 40,
    height: 40,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
  },

  // --- ESTILOS DEL FOOTER (TAB BAR) ---
  tabBar: {
    flexDirection: 'row',
    height: 70,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingBottom: Platform.OS === 'ios' ? 20 : 10,
  },
  tabItem: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  tabText: {
    fontSize: aplicarEscala(11),
    color: '#94A3B8',
    marginTop: 4,
    fontWeight: '500',
  },
  tabTextActive: {
    color: '#4D6BFE',
    fontWeight: '700',
  },

  // --- EXTRAS PARA EL HEADER DEL CHAT ---
  avatarContainer: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    backgroundColor: '#FEF3C7',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  statusDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#22C55E',
    position: 'absolute',
    bottom: 0,
    right: 0,
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  activityCanvas: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#E2E8F0',
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
    margin: 20,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  canvasHint: {
    color: '#94A3B8',
    marginTop: 12,
    fontSize: aplicarEscala(16),
    fontWeight: '500',
    textAlign: 'center',
  },
  actionPanel: {
    backgroundColor: '#FFFFFF',
    padding: 20,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderWidth: 1,
    borderColor: '#F1F5F9',
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -3 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
  },
  colorPicker: {
    width: 48,
    height: 48,
    borderRadius: 24,
    marginRight: 15,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: 'transparent',
  },

  colorPickerSelected: {
    borderColor: '#334155',
    transform: [{ scale: 1.1 }], 
  },
  iconButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#6366F1',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
  },
  // ==========================================
  // SECCIÓN: RECORDATORIOS (LISTADO)
  // ==========================================
  headerActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  headerButtonsGroup: {
    flexDirection: 'row',
  },
  dateHeaderContainer: {
    alignItems: 'center', 
    marginVertical: 20,
  },
  emptyStateContainer: {
    alignItems: 'center', 
    marginTop: 50,
  },
  emptyStateText: {
    color: '#718096', 
    marginTop: 10,
    fontSize: aplicarEscala(16),
    fontWeight: '500',
  },
  menuCardCompleted: {
    borderColor: '#4ADE80', 
    borderWidth: 1.5, 
    opacity: 0.8,
  },
  reminderInfoBody: {
    flex: 1,
  },
  reminderTopRow: {
    flexDirection: 'row', 
    alignItems: 'center', 
    marginBottom: 6,
  },
  timeBadge: {
    backgroundColor: '#F1F5F9', 
    paddingHorizontal: 8, 
    paddingVertical: 3, 
    borderRadius: 6, 
    marginRight: 8, 
    flexDirection: 'row', 
    alignItems: 'center',
  },
  timeBadgeText: {
    color: '#4D6BFE', 
    fontWeight: 'bold', 
    fontSize: aplicarEscala(11), 
    marginLeft: 4,
  },
  completedBadge: {
    backgroundColor: '#DCFCE7', 
    paddingHorizontal: 6, 
    paddingVertical: 2, 
    borderRadius: 4,
  },
  completedCheck: {
    color: '#16A34A', 
    fontSize: aplicarEscala(10), 
    fontWeight: 'bold',
  },
  reminderFooterRow: {
    flexDirection: 'row', 
    marginTop: 8, 
    alignItems: 'center',
  },
  typeDot: {
    width: 6, 
    height: 6, 
    borderRadius: 3, 
    marginRight: 6,
  },
  typeTabText: {
    fontSize: aplicarEscala(11), 
    color: '#94A3B8', 
    fontWeight: '600',
    textTransform: 'capitalize',
  },
  centeredLoader: {
    marginTop: 50,
  },
  calendarCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 10,
    marginBottom: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 3,
  },
  calendarTheme: {
    calendarBackground: '#FFFFFF',
    selectedDayBackgroundColor: '#4D6BFE',
    todayTextColor: '#4D6BFE',
    arrowColor: '#4D6BFE',
    textMonthFontWeight: '800',
    textDayHeaderFontWeight: '600',
    dotStyle: { width: 6, height: 6, borderRadius: 3 }
  },
  inputLabel: {
    fontSize: aplicarEscala(13),
    color: '#64748B',
    marginBottom: 8,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  textInput: {
    backgroundColor: '#F1F5F9',
    padding: 14,
    borderRadius: 12,
    marginBottom: 20,
    fontSize: aplicarEscala(16),
    color: '#1E293B',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  textArea: {
    minHeight: 100,
    textAlignVertical: 'top',
  },
  dateTimeContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 25,
  },
  dateTimeButton: {
    backgroundColor: '#EEF2FF',
    padding: 15,
    borderRadius: 12,
    flex: 0.48,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  dateTimeText: {
    color: '#4D6BFE',
    fontWeight: 'bold',
    marginLeft: 8,
  },
  btnPrimary: {
    backgroundColor: '#4D6BFE',
    padding: 18,
    borderRadius: 15,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 12,
  },
  btnDangerOutline: {
    padding: 15,
    borderRadius: 15,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FECACA',
    marginTop: 10,
  },
  gridContainer: {
    padding: 10,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderColor: '#eee',
  },
  gridRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  chipTema: {
    width: '31%', 
    height: 40,
    backgroundColor: '#F0F4FF',
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#E0E7FF',
  },
  chipTemaText: {
    fontSize: aplicarEscala(13),
    fontWeight: 'bold',
    color: '#334155',
    textAlign: 'center',
  },
  subtemasContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 10,
    paddingLeft: 5,
  },
  btnSubtema: {
    backgroundColor: '#fff',
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#334155',
    marginRight: 8,
    marginBottom: 8,
  },
  btnSubtemaText: {
    color: '#334155',
    fontSize: aplicarEscala(12),
    fontWeight: '700',
  },
  // --- INDICADOR DE ESCRITURA ---
writingIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#F1F5F9',
    padding: 8,
    borderRadius: 12,
    marginLeft: 5,
    marginBottom:10,
  },
  writingText: {
    marginLeft: 5,
    color: '#64748B',
    fontSize: aplicarEscala(12),
    fontWeight: '600',
  },
  headerTextContainer: {
    marginLeft: 12,
  },
  headerTitle: {
    fontSize: aplicarEscala(17),
    fontWeight: '700',
    color: '#1E293B',
  },
  headerStatus: {
    fontSize: aplicarEscala(11),
    color: '#22C55E',
    fontWeight: '600',
  },
  botIcon: {
    width: 35,
    height: 35,
  },
  headerInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  infoBox: {
    marginTop: 20,
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    borderStyle: 'dashed', 
  },
  infoIconCircle: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    backgroundColor: '#FFFBEB',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  infoTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1E293B',
    marginBottom: 4,
  },
  infoText: {
    fontSize: 14,
    color: '#64748B',
    lineHeight: 20,
    fontStyle: 'italic',
  },
    musicCard: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 16,
    flexDirection: 'row', 
    marginBottom: 16,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    alignItems: 'center',
  },
  musicCardContainer: {
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 14,
    marginBottom: 16,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
  },
  musicCardRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  musicImageContainer: {
    width: 55,
    height: 55,
    borderRadius: 12,
    overflow: 'hidden',
  },
  musicImageThumb: {
    width: '100%',
    height: '100%',
  },
  musicImagePlaceholder: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 12,
  },
  musicIconContainer: {
    width: 65,
    height: 65,
    borderRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  musicTextContainer: {
    flex: 1,
    marginLeft: 15,
    marginRight: 10,
  },
  musicCardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#334155',
  },
  musicCardDescription: {
    fontSize: 13,
    color: '#64748B',
    marginTop: 2,
  },
  musicBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
  },
  musicBadgePlaySection: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  musicBadgeText: {
    fontSize: 12,
    fontWeight: '700',
    marginLeft: 4,
  },
  musicSeparator: {
    marginHorizontal: 8,
    color: '#CBD5E1',
    fontSize: 14,
  },
    musicBadgeMomentSection: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  momentoTextInline: {
    fontSize: 12,
    color: '#64748B',
    marginLeft: 4,
    fontWeight: '500',
  },
  musicPlayButtonCircle: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  musicProgresoWrapper: {
    marginTop: 15,
    paddingHorizontal: 4,
  },
  musicBarraFondo: {
    height: 6,
    backgroundColor: '#E2E8F0',
    borderRadius: 3,
    overflow: 'hidden',
  },
  musicBarraRelleno: {
    height: '100%',
  },
  musicTiempos: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 5,
  },
  musicTiempoTexto: {
    fontSize: 11,
    color: '#94A3B8',
  },
  musicScrollContainer: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 40,
  },
  canvasDeleteButton: {
    padding: 8,
    backgroundColor: '#FFF1F2',
    borderRadius: 12,
  },
  canvasWrapper: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  canvasContainer: {
    width: CANVAS_SIZE, 
    height: CANVAS_SIZE + 120, 
    backgroundColor: 'white', 
    borderRadius: 25, 
    elevation: 10,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 15,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: '#E2E8F0',
  },
  canvasFooter: {
    marginHorizontal: 0,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    paddingTop: 10,
    marginBottom: 0,
    paddingHorizontal: 15,
    shadowOffset: { width: 0, height: -10 },
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 20,
  },
  canvasTools: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  canvasTool: {
    width: 45,
    height: 45,
    borderRadius: 15,
    backgroundColor: '#F1F5F9',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  canvasColorCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    marginRight: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  canvasActiveColorCircle: {
    borderWidth: 3,
    borderColor: '#334155',
    
  },
  canvasStatusText: {
    textAlign: 'center',
    color: '#94A3B8',
    fontWeight: 'bold',
    fontSize: 12,
    letterSpacing: 1.5,
  },
    tarjetaLectura: {
    width: '100%',
    height: 220,
    backgroundColor: 'white',
    borderRadius: 25,
    marginBottom: 20,
    overflow: 'hidden',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  contenedorImagenCorteLectura: {
    width: '100%',
    height: '100%',
    position: 'relative',
  },
  imagenLectura: {
    width: '100%',
    height: '100%',
  },
  corteOblicuoLectura: {
    position: 'absolute',
    bottom: -1,
    left: 0,
    right: -5,
    height: 120,
    backgroundColor: 'white',
    transform: [{ skewY: '-5deg' }, { translateY: 30 }],
  },
  infoCapaLectura: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  tituloListaLectura: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1E293B',
    lineHeight: 28,
  },
  badgeListaLectura: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 5,
    gap: 5,
  },
  tiempoListaLectura: {
    color: '#64748B',
    fontSize: 14,
    fontWeight: '600',
  },
  circuloLectura: {
    width: 35,
    height: 35,
    borderRadius: 27,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
  },
  portadaLecturaContainer: {
    width: '100%',
    height: 220,
    backgroundColor: '#000',
    position: 'relative',
  },
  imagenLecturaPortada: {
    width: '100%',
    height: '100%',
    opacity: 0.8,
  },
  imagenLecturaPlaceholder: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  overlayLecturaTitulo: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 20,
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },
  tituloTextoLectura: {
    fontSize: 26,
    fontWeight: 'bold',
    color: '#1E293B',
    textAlign: 'center',
  },
  divisorLectura: {
    height: 4,
    width: 50,
    alignSelf: 'center',
    marginTop: 8,
    borderRadius: 2,
  },
  controlesInferioresLectura: { 
    position: 'absolute', 
    bottom: 0, 
    left: 0, 
    right: 0, 
    backgroundColor: 'white', 
    borderTopLeftRadius: 30, 
    borderTopRightRadius: 30, 
    paddingTop: 10, 
    paddingHorizontal: 20, 
    elevation: 25,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -10 },
    shadowOpacity: 0.1,
    shadowRadius: 10,
  },
  containerProgresoLectura: { 
    height: 6, 
    backgroundColor: '#E2E8F0', 
    borderRadius: 3, 
    width: '100%', 
    marginBottom: 15, 
    overflow: 'hidden' 
  },
  barraProgresoLectura: { 
    height: '100%', 
    borderRadius: 3 
  },
  botonesRowLectura: { 
    flexDirection: 'row', 
    justifyContent: 'space-between', 
    alignItems: 'center' 
  },
  grupoBotonesLectura: { 
    flexDirection: 'row', 
    backgroundColor: '#F1F5F9', 
    borderRadius: 15, 
    padding: 5 
  },
  botonControlLectura: { 
    padding: 12, 
    marginHorizontal: 2 
  },
  botonVozLectura: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    paddingHorizontal: 20, 
    paddingVertical: 12, 
    borderRadius: 20, 
    gap: 8 
  },
  textVozLectura: { 
    color: 'white', 
    fontWeight: '700', 
    fontSize: 16 
  }
});